apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: /etc/slack/slack-token.txt
    username: Alarm
    icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png 
  subscriptions: |
    - recipients:
      - slack:alert
      triggers:
      - on-sync-status-unknown
      - on-sync-failed
      - on-health-degraded
      - on-deployed
      - on-sync-succeeded
